language: python

python:
  - "3.7"
  - "3.8"

install:
  - pip install black coverage coveralls isort mypy pytest tomlkit

script:
  - python -m coverage run -m pytest
  - python -m isort --check-only .
  - python -m black --check --skip-string-normalization .
  - python -m mypy --no-strict-optional --ignore-missing-imports phantomconfig tests

after_success:
  - python -m coveralls

notifications:
  email:
    recipients:
      - d.mentiplay@gmail.com
    on_success: change
    on_failure: always
