language: python

python:
  - "3.7"

install:
  - pip install black coverage coveralls isort mypy pytest tomlkit

script:
  - python -m coverage run -m pytest
  - isort --check-only -rc
  - black --check --skip-string-normalization .
  - mypy --no-strict-optional --ignore-missing-imports phantomconfig tests

after_success:
  - coveralls

notifications:
  email:
    recipients:
      - d.mentiplay@gmail.com
    on_success: change
    on_failure: always
